title: Josef Gm√ºr
logo: /cv_pic-modified_50.png
description: |
  <a href="https://www.linkedin.com/in/josef-gmuer/">LinkedIn</a>
  <a href="mailto:josefgmur@gmail.com">josefgmur@gmail.com</a>


theme: jekyll-theme-minimal


